#!/bin/sh
#
# Copyright (c) <2013> <Radware Ltd.> and others.  All rights reserved.
#
# This program and the accompanying materials are made available under the terms of the Eclipse Public License
# v1.0 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v10.html
# @author Konstantin Pozdeev
# @version 0.1
#

getent group defense4all >/dev/null || groupadd -r defense4all
getent passwd defense4all >/dev/null || \
useradd -d /usr/share/defense4all -g defense4all -M -r defense4all
exit 0
